name: test-conda-env
channels:
- conda-forge
- nodefaults

dependencies:
- python=3
- git
- numpy
- libhwloc=1
- pocl
- mako
- pyopencl
- islpy
- gmsh

# Needed for nodal-DG interop
- oct2py

# for Pytential
- cython

# for pymetis
- pybind11

# Only needed to make pylint succeed
- matplotlib

- pip
