name: test-conda-env
channels:
- conda-forge
- nodefaults

dependencies:
- python=3
- git
- libhwloc=2
- numpy
# 3.1 needed for SVM functionality
- pocl>=3.1
- mako
- pyopencl
- islpy
- gmsh

# Needed for nodal-DG interop
- oct2py

# for Pytential
- cython

# for pymetis
- pybind11

# for MPI-based tests
- openmpi
- mpi4py

# for xdmf/hdf5 visualizer
- h5py=*=mpi_openmpi*

# Only needed to make pylint succeed
- matplotlib-base

- pip
