[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "meshmode"
version = "2024.0"
description = "High-order polynomial discretizations of and on meshes"
readme = "README.rst"
license = "MIT"
authors = [
    { name = "Andreas Kloeckner", email = "inform@tiker.net" },
]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Other Audience",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
]
dependencies = [
    "arraycontext>=2021.1",
    "gmsh-interop>=2021.1",
    "loopy>=2024.1",
    "modepy>=2021.1",
    "numpy",
    "pymbolic>=2022.2",
    "pytools>=2025.2",
    "recursivenodes",
    "typing_extensions>=4.10",
]

[project.optional-dependencies]
doc = [
    "furo",
    "sphinx>=4",
    "sphinx-copybutton",
]
test = [
    "pylint",
    "pytest",
    "ruff",
]
visualization = [
    "h5py",
    "pyvisfile>=2022.1",
]

[project.urls]
Documentation = "https://documen.tician.de/meshmode"
Repository = "https://github.com/inducer/meshmode"

[tool.hatch.build.targets.sdist]
exclude = [
  "/.git*",
  "/doc/_build",
  "/.editorconfig",
  "/run-*.sh",
  "/.basedpyright",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
extend-select = [
    "B",    # flake8-bugbear
    "C",    # flake8-comprehensions
    "E",    # pycodestyle
    "F",    # pyflakes
    "G",    # flake8-logging-format
    "I",    # flake8-isort
    "N",    # pep8-naming
    "NPY",  # numpy
    "Q",    # flake8-quotes
    "RUF",  # ruff
    "TC",   # flake8-type-checking
    "UP",   # pyupgrade
    "W",    # pycodestyle
]
extend-ignore = [
    "C90",  # McCabe complexity
    "missing-whitespace-around-arithmetic-operator",
    "multiple-spaces-after-comma",
    "tab-after-comma",
    "no-space-after-block-comment",
    "module-import-not-at-top-of-file",
    "invalid-function-name",
    "invalid-argument-name",
    "non-lowercase-variable-in-function",
    "error-suffix-on-exception-name",
    "f-string",
    "non-empty-init-module",
    "type-check-without-type-error",
    "collapsible-if",
]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = [
    "pytools",
    "pyopencl",
    "loopy",
    "arraycontext",
    "gmsh_interop",
    "pyvisfile",
    "modepy",
    "pytato",
    "pymbolic",
    "pymetis",
    "firedrake",
]
known-local-folder = [
    "meshmode",
]
lines-after-imports = 2
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.per-file-ignores]
"examples/*.py" = ["missing-required-import"]
"doc/conf.py" = ["missing-required-import", "exec-builtin"]
"test/test_*.py" = ["exec-builtin"]

[tool.pytest.ini_options]
markers = [
    "mpi: test requires MPI",
    "octave: test requires Octave",
]

[tool.typos.default]
extend-ignore-re = [
  "(?Rm)^.*(#|//)\\s*spellchecker:\\s*disable-line$"
]

[tool.typos.default.extend-words]
# as in pt_typ, an import only used for type checking
"typ" = "typ"

"PN" = "PN"
"nd" = "nd"
# TODO: needed by deprecated MPIMeshDistributor.is_mananger_rank
"mananger" = "mananger"

[tool.basedpyright]
pythonVersion = "3.12"
pythonPlatform = "All"

reportImplicitStringConcatenation = "none"
reportUnnecessaryIsInstance = "none"
reportUnusedCallResult = "none"
reportExplicitAny = "none"
reportUnusedParameter = "hint"

reportPrivateUsage = "hint"
reportAny = "none"
reportUnreachable = "hint"

# This reports even cycles that are qualified by 'if TYPE_CHECKING'. Not what
# we care about at this moment.
# https://github.com/microsoft/pyright/issues/746
reportImportCycles = "none"

ignore = [
    "doc/conf.py",
    ".venv",
]

[[tool.basedpyright.executionEnvironments]]
root = "test"
reportArgumentType = "hint"
reportAttributeAccessIssue = "hint"
reportMissingImports = "none"
reportMissingParameterType = "none"
reportMissingTypeStubs = "none"
reportUnknownArgumentType = "none"
reportUnknownMemberType = "hint"
reportUnknownParameterType = "none"
reportUnknownVariableType = "none"
reportUnknownLambdaType = "hint"
reportOperatorIssue = "hint"
reportPossiblyUnboundVariable = "hint"
reportPrivateUsage = "none"
reportUnusedImport = "hint"


[[tool.basedpyright.executionEnvironments]]
root = "examples"
reportArgumentType = "hint"
reportAttributeAccessIssue = "hint"
reportMissingImports = "none"
reportMissingParameterType = "none"
reportMissingTypeStubs = "none"
reportUnknownArgumentType = "none"
reportUnknownMemberType = "hint"
reportUnknownParameterType = "none"
reportUnknownVariableType = "none"
reportUnknownLambdaType = "hint"
reportOperatorIssue = "hint"
reportPossiblyUnboundVariable = "hint"
reportPrivateUsage = "none"

reportGeneralTypeIssues = "hint"

[[tool.basedpyright.executionEnvironments]]
root = "meshmode/interop/firedrake"
reportMissingImports = "none"
reportCallIssue = "hint"
reportArgumentType = "hint"

[[tool.basedpyright.executionEnvironments]]
root = "meshmode/interop/nodal_dg.py"
reportMissingImports = "none"
reportOptionalMemberAccess = "none"
reportOptionalSubscript = "none"

[[tool.basedpyright.executionEnvironments]]
root = "meshmode/discretization/visualization.py"
reportMissingImports = "none"
